// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56s90z-2zM8w8wAR72JPXXfcZFUp0GCQ',
    appId: '1:493701541920:web:6b826c195b715b59f7cc45',
    messagingSenderId: '493701541920',
    projectId: 'vardaan-413611',
    authDomain: 'vardaan-413611.firebaseapp.com',
    storageBucket: 'vardaan-413611.appspot.com',
    measurementId: 'G-C1YHL5GTPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyi42z775nMkRaD8W1fIcwJipkBkJK8iQ',
    appId: '1:493701541920:android:6e58596a9811e59bf7cc45',
    messagingSenderId: '493701541920',
    projectId: 'vardaan-413611',
    storageBucket: 'vardaan-413611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADWJX6LJOay2LScwskLNMIIvW87bkh7rk',
    appId: '1:493701541920:ios:40826800e29ae6b7f7cc45',
    messagingSenderId: '493701541920',
    projectId: 'vardaan-413611',
    storageBucket: 'vardaan-413611.appspot.com',
    iosBundleId: 'com.health.vardaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADWJX6LJOay2LScwskLNMIIvW87bkh7rk',
    appId: '1:493701541920:ios:40826800e29ae6b7f7cc45',
    messagingSenderId: '493701541920',
    projectId: 'vardaan-413611',
    storageBucket: 'vardaan-413611.appspot.com',
    iosBundleId: 'com.health.vardaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56s90z-2zM8w8wAR72JPXXfcZFUp0GCQ',
    appId: '1:493701541920:web:dca1ce53f4c2dcb1f7cc45',
    messagingSenderId: '493701541920',
    projectId: 'vardaan-413611',
    authDomain: 'vardaan-413611.firebaseapp.com',
    storageBucket: 'vardaan-413611.appspot.com',
    measurementId: 'G-WXZGDHH5B7',
  );
}
